# Generated by Django 4.0.4 on 2022-08-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
